const activitiesEntry = [
  { id: 'a1b2c3d4e5f6', category: 'europe', name: 'Go for a walk', isForGoodWeather: true },
  { id: 'g7h8i9j0k1l2', category: 'europe', name: 'Have a picnic', isForGoodWeather: true },
  { id: 'm3n4o5p6q7r8', category: 'europe', name: 'Ride a bike', isForGoodWeather: true },
  { id: 'n1o2p3q4r5s6', category: 'europe', name: 'Visit a park', isForGoodWeather: true },
  { id: 't1u2v3w4x5y6', category: 'europe', name: 'Watch a movie', isForGoodWeather: false },
  { id: 'z7a8b9c0d1e2', category: 'europe', name: 'Bake a cake', isForGoodWeather: false },
  { id: 'f3g4h5i6j7k8', category: 'europe', name: 'Read a book', isForGoodWeather: false },
  { id: 'l9m0n1o2p3q4', category: 'europe', name: 'Do a puzzle', isForGoodWeather: false },
  { id: 's9t0u1v2w3x4', category: 'sahara', name: 'Go to the beach', isForGoodWeather: true },
  { id: 'r1s2t3u4v5w6', category: 'sahara', name: 'Ride a camel', isForGoodWeather: true },
  { id: 'x7y8z9a0b1c2', category: 'sahara', name: 'Explore sand dunes', isForGoodWeather: true },
  { id: 'd3e4f5g6h7i8', category: 'sahara', name: 'Visit an oasis', isForGoodWeather: true },
  { id: 'k7l8m9n0o1p2', category: 'sahara', name: 'Read a book', isForGoodWeather: false },
  { id: 'j1k2l3m4n5o6', category: 'sahara', name: 'Watch a documentary', isForGoodWeather: false },
  { id: 'p7q8r9s0t1u2', category: 'sahara', name: 'Do some yoga', isForGoodWeather: false },
  { id: 'v3w4x5y6z7a8', category: 'sahara', name: 'Try a new recipe', isForGoodWeather: false },
  { id: 'y5z6a7b8c9d0', category: 'arctic', name: 'Play outdoor sports', isForGoodWeather: true },
  { id: 'b1c2d3e4f5g6', category: 'arctic', name: 'Go sledding', isForGoodWeather: true },
  { id: 'h7i8j9k0l1m2', category: 'arctic', name: 'Build a snowman', isForGoodWeather: true },
  { id: 'n3o4p5q6r7s8', category: 'arctic', name: 'Take a hike', isForGoodWeather: true },
  { id: 'e1f2g3h4i5j6', category: 'arctic', name: 'Watch a movie', isForGoodWeather: false },
  { id: 't9u0v1w2x3y4', category: 'arctic', name: 'Knit a scarf', isForGoodWeather: false },
  { id: 'z5a6b7c8d9e0', category: 'arctic', name: 'Play board games', isForGoodWeather: false },
  { id: 'f1g2h3i4j5k6', category: 'arctic', name: 'Write a journal', isForGoodWeather: false },
  { id: 'q3r4s5t6u7v8', category: 'rainforest', name: 'Go bird watching', isForGoodWeather: true },
  { id: 'm9n0o1p2q3r4', category: 'rainforest', name: 'Take a nature walk', isForGoodWeather: true },
  { id: 's5t6u7v8w9x0', category: 'rainforest', name: 'Go canoeing', isForGoodWeather: true },
  { id: 'y1z2a3b4c5d6', category: 'rainforest', name: 'Have a picnic', isForGoodWeather: true },
  { id: 'w9x0y1z2a3b4', category: 'rainforest', name: 'Cook a new recipe', isForGoodWeather: false },
  { id: 'k3l4m5n6o7p8', category: 'rainforest', name: 'Watch a nature documentary', isForGoodWeather: false },
  { id: 'd7e8f9g0h1i2', category: 'rainforest', name: 'Paint a picture', isForGoodWeather: false },
  { id: 'j3k4l5m6n7o8', category: 'rainforest', name: 'Do indoor gardening', isForGoodWeather: false },
];

export default activitiesEntry;
